### ISSUE TITLE
Radio mode documentation

### ISSUE THREAD

**Issue by JeffersonBledsoe** [music-assistant/music-assistant.github.io#26]
Radio mode is an amazing feature, it would be nice to have it documented in a more defined way (especially the per-provider behaviour such as a track from Spotify using the `recommendations` endpoint to get Spotify to suggest similar tracks)

**Comment by OzGav** [comment]
Are you referring to the developer docs here?

**Comment by OzGav** [comment]
Ok. MA only ever uses the provider to construct the queue which is why it only works with certain providers. Can you provide more info about what else you would like to know about it? We have two sentences about it currently on here https://music-assistant.io/ui/

**Comment by OzGav** [comment]
Checking in again as to what additional info you think is needed?

**Comment by JeffersonBledsoe** [comment]
I hadn't seen the radio part in this documentation, good to see it's in there! It would be nice to get more details about `This will populate the queue with tracks based on the selected track`, as behaviour could be different for different providers, but I'm happy to close this as it's not really essentialy.

**Comment by OzGav** [comment]
Cool I will just add a bit more to indicate that behaviour will be dependant on the provider as suggested,
